[package]
name = "geometria_serializer"
version = "0.1.0"
edition = "2021"
exclude = ["tests/resources/"]

[dependencies]
geometria_derive = { path = "../derive" }
once_io = { git = "https://github.com/julionce/once_io" }